### ISSUE TITLE
STM32 boards custom options are not available

### ISSUE THREAD

**Issue by TzOk83** [arduino/arduino-pro-ide#195]
The STM32Duino package boards are impossible to select. No options available for them.

**Comment by ubidefeo** [comment]
hi @TzOk83 
you're going to have to add the `additional_url` to the CLI configuration file.
It can be a bit tricky but it's on the list to make that easily accessible via UI.

what platform are you on?
if you can find `arduino-cli.yaml` on your system you can add the custom core URL and the boards will show up in Boards Manager

You can see my config file below
```yaml
arduino_data: /Users/xxx/Library/arduino15
board_manager:
  additional_urls:
  - https://dl.espressif.com/dl/package_esp32_index.json
  - http://arduino.esp8266.com/stable/package_esp8266com_index.json
  - https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json
daemon:
  port: "50051"
directories:
  data: /Users/xxx/Library/Arduino15
  downloads: /Users/xxx/Library/Arduino15/staging
  user: /xxx/xxx/AppsDocuments/Arduino
logging:
  file: ""
  format: text
  level: info
proxy_type: auto
sketchbook_path: /xxx/xxx/AppsDocuments/Arduino
```
<img width="749" alt="Screenshot 2020-02-01 at 08 05 56" src="https://user-images.githubusercontent.com/1894487/73588479-d4f28400-44c9-11ea-992c-8dd7eeec23a5.png">
